version: '3.8'

networks:
  integration-test:

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: ":2565"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/assessment_test?sslmode=disable"
    ports:
      - "2565:2565"
    expose:
      - "2565"
    depends_on:
      - db
    networks:
      - integration-test

  it_tests:
    build: 
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - $PWD:/go/src/target
    environment:
      APP_URL: "http://app:2565"
    depends_on:
      - db
      - app
    networks:
      - integration-test

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assessment_test
    restart: on-failure
    networks:
      - integration-test
